// @START (CODE)
// @MARKER CASTING BY TITLE
// ==================================================================================================================
// His functions for how far a caster and an invoker have come: Aura Control and Piety Control gained
// per title, the title Spell Lore arrives, the ceilings on Aura Control and the Aura Pool, the rate the
// pool refills, and the invocations each devotion holds. Read by module/casting-rules.mjs, which the
// character's prepare step calls; the rules that COMBINE them (his setMagicDivineLore) are there.
//
// GENERATED by tools/extract/extract_casting.py from docs/reference/sheet-worker.js. Do not edit
// by hand: change his sheet or the extractor, and run it again.
//==================================================================================================================

import {
	castingRandom
} from "./casting-helpers.mjs";

// @MARKER HIS WORKING VARIABLES
// Every name his functions below assign without declaring. In his sheet each is one global
// shared by all of them, and so it is here: declared once, at module scope.
var devotionList, devotionListArray, lightFireSpells, newCastTimeValue, newModNum, shadowFrostSpells;
var tempAuraControlTitleMod, tempAuraRegenRate, tempCastTimeType, tempCastTimeValue, tempCastTimeValue2;
var tempCurrentTitle, tempFoundIn, tempMaxAC, tempMaxAP, tempNewCastingTime, tempPietyControlTitleMod;
var tempPractitionerTitle, tempRegenRate, tempStartingTitle, tempValue, tmpDevotionList, tmpDoubledRate;
var tmpModBoostNum, tmpNewAuraRegen, tmpStandardRegenNum, whenSpellLore;

// @MARKER divideWithMin (sheet-worker.js:25595)
	function divideWithMin(tmpDividend, tmpDivisor) {
		tempValue=parseInt(tmpDividend/tmpDivisor);
		if (tempValue<1) { tempValue=1; }
		return tempValue;
	}

// @MARKER getSpellLoreWhen (sheet-worker.js:95591)
	export function getSpellLoreWhen(tempClassname) { // or equiv. (like Lightfire Lore or Shadowfrost Lore)
		whenSpellLore=0;
		switch(tempClassname) {
			case "Acrobat":            whenSpellLore=0; break;
			case "Alchemist":          whenSpellLore=8; break;
			case "Arcanist":           whenSpellLore=9; break;
			case "Archer":             whenSpellLore=0; break;
			case "Archer(Arcane)":     whenSpellLore=6; break;
			case "Archer(Zen)":        whenSpellLore=0; break;
			case "Assassin":           whenSpellLore=0; break;
			case "Bandit":             whenSpellLore=0; break;
			case "Banisher":           whenSpellLore=0; break;
			case "Bard":               whenSpellLore=14; break;
			case "Battlemancer":       whenSpellLore=9; break;
			case "Beastmaster":        whenSpellLore=0; break;
			case "Beguiler":           whenSpellLore=0; break;
			case "Berserker":          whenSpellLore=0; break;
			case "Border Scout":       whenSpellLore=0; break;
			case "Bounty Hunter":      whenSpellLore=0; break;
			case "Buccaneer":          whenSpellLore=0; break;
			case "Cacophonist":        whenSpellLore=0; break;
			case "Cajoler":            whenSpellLore=0; break;
			case "Cavalier":           whenSpellLore=0; break;
			case "Channeler":          whenSpellLore=8; break;
			case "Conqueror":          whenSpellLore=0; break;
			case "Crypt Robber":       whenSpellLore=0; break;
			case "Curse Breaker":      whenSpellLore=7; break;
			case "Delver":             whenSpellLore=0; break;
			case "Dervish":            whenSpellLore=0; break;
			case "Dreamer":            whenSpellLore=10; break;
			case "Druid":              whenSpellLore=12; break;
			case "Duelist":            whenSpellLore=0; break;
			case "Elemental Dancer":   whenSpellLore=0; break;
			case "Elementalist":       whenSpellLore=0; break;
			case "Enchanter":          whenSpellLore=8; break;
			case "Exorcist":           whenSpellLore=0; break;
			case "Explorer":           whenSpellLore=0; break;
			case "Gypsy":              whenSpellLore=0; break;
			case "Harbinger":          whenSpellLore=0; break;
			case "Harmonist":          whenSpellLore=0; break;
			case "Healer":             whenSpellLore=0; break;
			case "Heretic":            whenSpellLore=0; break;
			case "Hermeticist":        whenSpellLore=0; break;
			case "Hero":               whenSpellLore=0; break;
			case "Hunter":             whenSpellLore=0; break;
			case "Illuminator":        whenSpellLore=7; break;
			case "Innominate":         whenSpellLore=0; break;
			case "Inquisitor":         whenSpellLore=0; break;
			case "Intercessor":        whenSpellLore=0; break;
			case "Investigator":       whenSpellLore=0; break;
			case "Jester":             whenSpellLore=0; break;
			case "Kineticist":         whenSpellLore=0; break;
			case "Knight":             whenSpellLore=0; break;
			case "Knight(Dark)":       whenSpellLore=0; break;
			case "Knight(Death)":      whenSpellLore=0; break;
			case "Legendier":          whenSpellLore=0; break;
			case "Luckster":           whenSpellLore=0; break;
			case "Mage":               whenSpellLore=7; break;
			case "Martial Artist":     whenSpellLore=0; break;
			case "Medium":             whenSpellLore=0; break;
			case "Mentalist":          whenSpellLore=13; break;
			case "Minstrel":           whenSpellLore=11; break;
			case "Missionary":         whenSpellLore=0; break;
			case "Monk":               whenSpellLore=0; break;
			case "Mounted Archer":     whenSpellLore=8; break;
			case "Necromancer":        whenSpellLore=0; break;
			case "Obscuratum":         whenSpellLore=0; break;
			case "Paladin":            whenSpellLore=0; break;
			case "Plunderer":          whenSpellLore=0; break;
			case "Priest":             whenSpellLore=0; break;
			case "Priest(Dark)":       whenSpellLore=0; break;
			case "Psychokineticist":   whenSpellLore=0; break;
			case "Ranger":             whenSpellLore=0; break;
			case "Ritual Leader":      whenSpellLore=0; break;
			case "Rogue":              whenSpellLore=0; break;
			case "Runesmith":          whenSpellLore=0; break;
			case "Sage":               whenSpellLore=8; break;
			case "Seer":               whenSpellLore=0; break;
			case "Shadow Stalker":     whenSpellLore=0; break;
			case "Shadowfrost Caster": whenSpellLore=7; break;
			case "Shaman":             whenSpellLore=0; break;
			case "Shaman(Drum)":       whenSpellLore=0; break;
			case "Shaman(Rune)":       whenSpellLore=0; break;
			case "Sorcerer":           whenSpellLore=0; break;
			case "Summoner":           whenSpellLore=0; break;
			case "Trickster":          whenSpellLore=10; break;
			case "Vivisectionist":     whenSpellLore=9; break;
			case "Warden":             whenSpellLore=0; break;
			case "Warrior":            whenSpellLore=0; break;
			case "Wilder":             whenSpellLore=0; break;
			case "Witch(Black)":       whenSpellLore=0; break;
			case "Witch(Gray)":        whenSpellLore=11; break;
			case "Witch(White)":       whenSpellLore=11; break;
			case "Witch Hunter":       whenSpellLore=11; break;
			case "GME":                whenSpellLore=0; break;
		}
		return whenSpellLore;
	}

// @MARKER getPietyControlTitleMod (sheet-worker.js:96103)
	export function getPietyControlTitleMod(tempClassname) {
		tempPietyControlTitleMod=0;
		switch(tempClassname) {
			case "Acrobat":            tempPietyControlTitleMod=0; break;
			case "Alchemist":          tempPietyControlTitleMod=2; break;
			case "Arcanist":           tempPietyControlTitleMod=0; break;
			case "Archer":             tempPietyControlTitleMod=0; break;
			case "Archer(Arcane)":     tempPietyControlTitleMod=0; break;
			case "Archer(Zen)":        tempPietyControlTitleMod=2; break;
			case "Assassin":           tempPietyControlTitleMod=0; break;
			case "Bandit":             tempPietyControlTitleMod=0; break;
			case "Banisher":           tempPietyControlTitleMod=2; break;
			case "Bard":               tempPietyControlTitleMod=0; break;
			case "Battlemancer":       tempPietyControlTitleMod=0; break;
			case "Beastmaster":        tempPietyControlTitleMod=0; break;
			case "Beguiler":           tempPietyControlTitleMod=0; break;
			case "Berserker":          tempPietyControlTitleMod=0; break;
			case "Border Scout":       tempPietyControlTitleMod=0; break;
			case "Bounty Hunter":      tempPietyControlTitleMod=0; break;
			case "Buccaneer":          tempPietyControlTitleMod=0; break;
			case "Cacophonist":        tempPietyControlTitleMod=0; break;
			case "Cajoler":            tempPietyControlTitleMod=0; break;
			case "Cavalier":           tempPietyControlTitleMod=0; break;
			case "Channeler":          tempPietyControlTitleMod=2; break;
			case "Conqueror":          tempPietyControlTitleMod=0; break;
			case "Crypt Robber":       tempPietyControlTitleMod=0; break;
			case "Curse Breaker":      tempPietyControlTitleMod=2; break;			
			case "Delver":             tempPietyControlTitleMod=0; break;
			case "Dervish":            tempPietyControlTitleMod=0; break;
			case "Dreamer":            tempPietyControlTitleMod=0; break;
			case "Druid":              tempPietyControlTitleMod=2; break;
			case "Duelist":            tempPietyControlTitleMod=0; break;
			case "Elemental Dancer":   tempPietyControlTitleMod=0; break;
			case "Elementalist":       tempPietyControlTitleMod=0; break;
			case "Enchanter":          tempPietyControlTitleMod=0; break;
			case "Exorcist":           tempPietyControlTitleMod=2; break;
			case "Explorer":           tempPietyControlTitleMod=0; break;
			case "Gypsy":              tempPietyControlTitleMod=0; break;
			case "Harbinger":          tempPietyControlTitleMod=2; break;
			case "Harmonist":          tempPietyControlTitleMod=0; break;
			case "Healer":             tempPietyControlTitleMod=2; break;
			case "Heretic":            tempPietyControlTitleMod=2; break;
			case "Hermeticist":        tempPietyControlTitleMod=0; break;
			case "Hero":               tempPietyControlTitleMod=0; break;
			case "Hunter":             tempPietyControlTitleMod=0; break;
			case "Illuminator":        tempPietyControlTitleMod=0; break;
			case "Innominate":         tempPietyControlTitleMod=2; break;
			case "Inquisitor":         tempPietyControlTitleMod=2; break;
			case "Intercessor":        tempPietyControlTitleMod=2; break;
			case "Investigator":       tempPietyControlTitleMod=0; break;
			case "Jester":             tempPietyControlTitleMod=0; break;
			case "Kineticist":         tempPietyControlTitleMod=0; break;
			case "Knight":             tempPietyControlTitleMod=2; break;
			case "Knight(Dark)":       tempPietyControlTitleMod=2; break;
			case "Knight(Death)":      tempPietyControlTitleMod=2; break;
			case "Legendier":          tempPietyControlTitleMod=0; break;
			case "Luckster":           tempPietyControlTitleMod=0; break;
			case "Mage":               tempPietyControlTitleMod=0; break;
			case "Martial Artist":     tempPietyControlTitleMod=0; break;
			case "Medium":             tempPietyControlTitleMod=2; break;
			case "Mentalist":          tempPietyControlTitleMod=0; break;
			case "Minstrel":           tempPietyControlTitleMod=0; break;
			case "Missionary":         tempPietyControlTitleMod=2; break;
			case "Monk":               tempPietyControlTitleMod=2; break;
			case "Mounted Archer":     tempPietyControlTitleMod=0; break;
			case "Necromancer":        tempPietyControlTitleMod=2; break;
			case "Obscuratum":         tempPietyControlTitleMod=0; break;
			case "Paladin":            tempPietyControlTitleMod=2; break;
			case "Plunderer":          tempPietyControlTitleMod=0; break;
			case "Priest":             tempPietyControlTitleMod=2; break;
			case "Priest(Dark)":       tempPietyControlTitleMod=2; break;
			case "Psychokineticist":   tempPietyControlTitleMod=0; break;
			case "Ranger":             tempPietyControlTitleMod=2; break;
			case "Ritual Leader":      tempPietyControlTitleMod=2; break;
			case "Rogue":              tempPietyControlTitleMod=0; break;
			case "Runesmith":          tempPietyControlTitleMod=0; break;
			case "Sage":               tempPietyControlTitleMod=2; break;
			case "Seer":               tempPietyControlTitleMod=2; break;
			case "Shadow Stalker":     tempPietyControlTitleMod=0; break;
			case "Shadowfrost Caster": tempPietyControlTitleMod=0; break;
			case "Shaman":             tempPietyControlTitleMod=2; break;
			case "Shaman(Drum)":       tempPietyControlTitleMod=2; break;
			case "Shaman(Rune)":       tempPietyControlTitleMod=2; break;
			case "Sorcerer":           tempPietyControlTitleMod=0; break;
			case "Summoner":           tempPietyControlTitleMod=0; break;
			case "Trickster":          tempPietyControlTitleMod=0; break;
			case "Vivisectionist":     tempPietyControlTitleMod=0; break;
			case "Warden":             tempPietyControlTitleMod=2; break;
			case "Warrior":            tempPietyControlTitleMod=0; break;
			case "Wilder":             tempPietyControlTitleMod=0; break;
			case "Witch(Black)":       tempPietyControlTitleMod=2; break;
			case "Witch(Gray)":        tempPietyControlTitleMod=2; break;
			case "Witch(White)":       tempPietyControlTitleMod=2; break;
			case "Witch Hunter":       tempPietyControlTitleMod=0; break;
			case "GME":                tempPietyControlTitleMod=0; break;
		}
		return tempPietyControlTitleMod;
	}

// @MARKER getAuraControlTitleMod (sheet-worker.js:96202)
	export function getAuraControlTitleMod(tempClassname) {
		tempAuraControlTitleMod=0;
		switch(tempClassname) {
			case "Acrobat":            tempAuraControlTitleMod=0; break;
			case "Alchemist":          tempAuraControlTitleMod=2; break;
			case "Arcanist":           tempAuraControlTitleMod=2; break;
			case "Archer":             tempAuraControlTitleMod=0; break;
			case "Archer(Arcane)":     tempAuraControlTitleMod=2; break;
			case "Archer(Zen)":        tempAuraControlTitleMod=0; break;
			case "Assassin":           tempAuraControlTitleMod=0; break;
			case "Bandit":             tempAuraControlTitleMod=0; break;
			case "Banisher":           tempAuraControlTitleMod=0; break;
			case "Bard":               tempAuraControlTitleMod=2; break;
			case "Battlemancer":       tempAuraControlTitleMod=2; break;
			case "Beastmaster":        tempAuraControlTitleMod=0; break;
			case "Beguiler":           tempAuraControlTitleMod=0; break;
			case "Berserker":          tempAuraControlTitleMod=0; break;
			case "Border Scout":       tempAuraControlTitleMod=0; break;
			case "Bounty Hunter":      tempAuraControlTitleMod=0; break;
			case "Buccaneer":          tempAuraControlTitleMod=0; break;
			case "Cacophonist":        tempAuraControlTitleMod=0; break;
			case "Cajoler":            tempAuraControlTitleMod=0; break;
			case "Cavalier":           tempAuraControlTitleMod=0; break;
			case "Channeler":          tempAuraControlTitleMod=2; break;
			case "Conqueror":          tempAuraControlTitleMod=0; break;
			case "Crypt Robber":       tempAuraControlTitleMod=0; break;
			case "Curse Breaker":      tempAuraControlTitleMod=2; break;
			case "Delver":             tempAuraControlTitleMod=0; break;
			case "Dervish":            tempAuraControlTitleMod=0; break;
			case "Dreamer":            tempAuraControlTitleMod=2; break;
			case "Druid":              tempAuraControlTitleMod=2; break;
			case "Duelist":            tempAuraControlTitleMod=0; break;
			case "Elemental Dancer":   tempAuraControlTitleMod=0; break;
			case "Elementalist":       tempAuraControlTitleMod=0; break;
			case "Enchanter":          tempAuraControlTitleMod=2; break;
			case "Exorcist":           tempAuraControlTitleMod=0; break;
			case "Explorer":           tempAuraControlTitleMod=0; break;
			case "Gypsy":              tempAuraControlTitleMod=2; break;
			case "Harbinger":          tempAuraControlTitleMod=0; break;
			case "Harmonist":          tempAuraControlTitleMod=0; break;
			case "Healer":             tempAuraControlTitleMod=0; break;
			case "Heretic":            tempAuraControlTitleMod=0; break;
			case "Hermeticist":        tempAuraControlTitleMod=2; break;
			case "Hero":               tempAuraControlTitleMod=0; break;
			case "Hunter":             tempAuraControlTitleMod=0; break;
			case "Illuminator":        tempAuraControlTitleMod=2; break;
			case "Innominate":         tempAuraControlTitleMod=0; break;
			case "Inquisitor":         tempAuraControlTitleMod=0; break;
			case "Intercessor":        tempAuraControlTitleMod=0; break;
			case "Investigator":       tempAuraControlTitleMod=0; break;
			case "Jester":             tempAuraControlTitleMod=0; break;
			case "Kineticist":         tempAuraControlTitleMod=0; break;
			case "Knight":             tempAuraControlTitleMod=0; break;
			case "Knight(Dark)":       tempAuraControlTitleMod=0; break;
			case "Knight(Death)":      tempAuraControlTitleMod=0; break;
			case "Legendier":          tempAuraControlTitleMod=0; break;
			case "Luckster":           tempAuraControlTitleMod=0; break;
			case "Mage":               tempAuraControlTitleMod=2; break;
			case "Martial Artist":     tempAuraControlTitleMod=0; break;
			case "Medium":             tempAuraControlTitleMod=0; break;
			case "Mentalist":          tempAuraControlTitleMod=2; break;
			case "Minstrel":           tempAuraControlTitleMod=2; break;
			case "Missionary":         tempAuraControlTitleMod=0; break;
			case "Monk":               tempAuraControlTitleMod=0; break;
			case "Mounted Archer":     tempAuraControlTitleMod=0; break;
			case "Necromancer":        tempAuraControlTitleMod=2; break;
			case "Obscuratum":         tempAuraControlTitleMod=2; break;
			case "Paladin":            tempAuraControlTitleMod=0; break;
			case "Plunderer":          tempAuraControlTitleMod=0; break;
			case "Priest":             tempAuraControlTitleMod=0; break;
			case "Priest(Dark)":       tempAuraControlTitleMod=0; break;
			case "Psychokineticist":   tempAuraControlTitleMod=0; break;
			case "Ranger":             tempAuraControlTitleMod=0; break;
			case "Ritual Leader":      tempAuraControlTitleMod=2; break;
			case "Rogue":              tempAuraControlTitleMod=0; break;
			case "Runesmith":          tempAuraControlTitleMod=0; break;
			case "Sage":               tempAuraControlTitleMod=2; break;
			case "Seer":               tempAuraControlTitleMod=2; break;
			case "Shadow Stalker":     tempAuraControlTitleMod=0; break;
			case "Shadowfrost Caster": tempAuraControlTitleMod=2; break;
			case "Shaman":             tempAuraControlTitleMod=0; break;
			case "Shaman(Drum)":       tempAuraControlTitleMod=0; break;
			case "Shaman(Rune)":       tempAuraControlTitleMod=0; break;
			case "Sorcerer":           tempAuraControlTitleMod=2; break;
			case "Summoner":           tempAuraControlTitleMod=0; break;
			case "Trickster":          tempAuraControlTitleMod=2; break;
			case "Vivisectionist":     tempAuraControlTitleMod=2; break;
			case "Warden":             tempAuraControlTitleMod=0; break;
			case "Warrior":            tempAuraControlTitleMod=0; break;
			case "Wilder":             tempAuraControlTitleMod=1; break;
			case "Witch(Black)":       tempAuraControlTitleMod=2; break;
			case "Witch(Gray)":        tempAuraControlTitleMod=2; break;
			case "Witch(White)":       tempAuraControlTitleMod=2; break;
			case "Witch Hunter":       tempAuraControlTitleMod=0; break;
			case "GME":                tempAuraControlTitleMod=0; break;
		}
		return tempAuraControlTitleMod;
	}

// @MARKER getAuraRegenRate (sheet-worker.js:96301)
	export function getAuraRegenRate(tempClassname,tempTitle,tempCasterStartTitle,tempDoubleRegen,tempAuraRegenBonus) {
		tempAuraRegenRate="";
		tempStartingTitle=0;
		tempCurrentTitle=parseInt(tempTitle);
		if (tempClassname=="Elementalist" || tempClassname=="Beguiler" || tempClassname=="Kineticist" || tempClassname=="Sorcerer") { // even though these classes are not 'casters' they are treated as such for the aura regen they get for their aura related skills.
			tempStartingTitle=1;
		} else if (tempClassname=="Psychokineticist") { // even though these classes are not 'casters' they are treated as such for the aura regen they get for their aura related skills.
			tempStartingTitle=2;
		} else if (tempClassname=="Summoner") { // even though these classes are not 'casters' they are treated as such for the aura regen they get for their aura related skills.
			tempStartingTitle=3;
		} else if (tempClassname=="Elemental Dancer") { // even though these classes are not 'casters' they are treated as such for the aura regen they get for their aura related skills.
			tempStartingTitle=7;
		} else {// traditional caster (if not, ends up being 0)
			tempStartingTitle=parseInt(tempCasterStartTitle);
		}
		tempPractitionerTitle=0;
		tempPractitionerTitle=tempCurrentTitle-tempStartingTitle+1; // +1 because if titles match they are a 1st title practitoner
		if (tempPractitionerTitle<0) { tempPractitionerTitle=0; }
		switch(tempClassname) {
			case "Acrobat":            tempAuraRegenRate="1/per Hour"; break;
			case "Alchemist":          tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Arcanist":           tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Archer":             tempAuraRegenRate="1/per Hour"; break;
			case "Archer(Arcane)":     tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Archer(Zen)":        tempAuraRegenRate="1/per Hour"; break;
			case "Assassin":           tempAuraRegenRate="1/per Hour"; break;
			case "Bandit":             tempAuraRegenRate="1/per Hour"; break;
			case "Banisher":           tempAuraRegenRate="1/per Hour"; break;
			case "Bard":               tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Battlemancer":       tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Beastmaster":        tempAuraRegenRate="1/per Hour"; break;
			case "Beguiler":           tempAuraRegenRate=GetRegenRateSecondaryEquiv(tempPractitionerTitle); break;
			case "Berserker":          tempAuraRegenRate="1/per Hour"; break;
			case "Border Scout":       tempAuraRegenRate="1/per Hour"; break;
			case "Bounty Hunter":      tempAuraRegenRate="1/per Hour"; break;
			case "Buccaneer":          tempAuraRegenRate="1/per Hour"; break;
			case "Cacophonist":        tempAuraRegenRate="1/per Hour"; break;
			case "Cajoler":            tempAuraRegenRate="1/per Hour"; break;
			case "Cavalier":           tempAuraRegenRate="1/per Hour"; break;
			case "Channeler":          tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Conqueror":          tempAuraRegenRate="1/per Hour"; break;
			case "Crypt Robber":       tempAuraRegenRate="1/per Hour"; break;
			case "Curse Breaker":      tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Delver":             tempAuraRegenRate="1/per Hour"; break;
			case "Dervish":            tempAuraRegenRate="1/per Hour"; break;
			case "Dreamer":            tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Druid":              tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Duelist":            tempAuraRegenRate="1/per Hour"; break;
			case "Elemental Dancer":   tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Elementalist":       tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Enchanter":          tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Exorcist":           tempAuraRegenRate="1/per Hour"; break;
			case "Explorer":           tempAuraRegenRate="1/per Hour"; break;
			case "Gypsy":              tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Harbinger":          tempAuraRegenRate="1/per Hour"; break;
			case "Harmonist":          tempAuraRegenRate="1/per Hour"; break;
			case "Healer":             tempAuraRegenRate="1/per Hour"; break;
			case "Heretic":            tempAuraRegenRate="1/per Hour"; break;
			case "Hermeticist":        tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Hero":               tempAuraRegenRate="1/per Hour"; break;
			case "Hunter":             tempAuraRegenRate="1/per Hour"; break;
			case "Illuminator":        tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Innominate":         tempAuraRegenRate="1/per Hour"; break;
			case "Inquisitor":         tempAuraRegenRate="1/per Hour"; break;
			case "Intercessor":        tempAuraRegenRate="1/per Hour"; break;
			case "Investigator":       tempAuraRegenRate="1/per Hour"; break;
			case "Jester":             tempAuraRegenRate="1/per Hour"; break;
			case "Kineticist":         tempAuraRegenRate=GetRegenRateSecondaryEquiv(tempPractitionerTitle); break;
			case "Knight":             tempAuraRegenRate="1/per Hour"; break;
			case "Knight(Dark)":       tempAuraRegenRate="1/per Hour"; break;
			case "Knight(Death)":      tempAuraRegenRate="1/per Hour"; break;
			case "Legendier":          tempAuraRegenRate="1/per Hour"; break;
			case "Luckster":           tempAuraRegenRate="1/per Hour"; break;
			case "Mage":               tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Martial Artist":     tempAuraRegenRate="1/per Hour"; break;
			case "Medium":             tempAuraRegenRate="1/per Hour"; break;
			case "Mentalist":          tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Minstrel":           tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Missionary":         tempAuraRegenRate="1/per Hour"; break;
			case "Monk":               tempAuraRegenRate="1/per Hour"; break;
			case "Mounted Archer":     tempAuraRegenRate="1/per Hour"; break;
			case "Necromancer":        tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Obscuratum":         tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Paladin":            tempAuraRegenRate="1/per Hour"; break;
			case "Plunderer":          tempAuraRegenRate="1/per Hour"; break;
			case "Priest":             tempAuraRegenRate="1/per Hour"; break;
			case "Priest(Dark)":       tempAuraRegenRate="1/per Hour"; break;
			case "Psychokineticist":   tempAuraRegenRate=GetRegenRateSecondaryEquiv(tempPractitionerTitle); break;
			case "Ranger":             tempAuraRegenRate="1/per Hour"; break;
			case "Ritual Leader":      tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Rogue":              tempAuraRegenRate="1/per Hour"; break;
			case "Runesmith":          tempAuraRegenRate="1/per Hour"; break;
			case "Sage":               tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Seer":               tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Shadow Stalker":     tempAuraRegenRate="1/per Hour"; break;
			case "Shadowfrost Caster": tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Shaman":             tempAuraRegenRate="1/per Hour"; break;
			case "Shaman(Drum)":       tempAuraRegenRate="1/per Hour"; break;
			case "Shaman(Rune)":       tempAuraRegenRate="1/per Hour"; break;
			case "Sorcerer":           tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Summoner":           tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Trickster":          tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Vivisectionist":     tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Warden":             tempAuraRegenRate="1/per Hour"; break;
			case "Warrior":            tempAuraRegenRate="1/per Hour"; break;
			case "Wilder":             tempAuraRegenRate=GetRegenRateWildMagic(tempPractitionerTitle); break;
			case "Witch(Black)":       tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Witch(Gray)":        tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Witch(White)":       tempAuraRegenRate=GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle); break;
			case "Witch Hunter":       tempAuraRegenRate="1/per Hour"; break;
			case "GME":                tempAuraRegenRate="1/per Hour"; break;
		}
		if (tempAuraRegenRate=="") { tempAuraRegenRate="1/per Hour"; } // 1 per hour is the minimum.
		if (tempAuraRegenBonus!="") { tempAuraRegenRate=addHighAuraRegenBoost(tempAuraRegenRate, tempAuraRegenBonus); }
		if (tempDoubleRegen=="on") { tempAuraRegenRate=getDoubleRegenRate(tempAuraRegenRate); } // double it!
		return tempAuraRegenRate;
	}

// @MARKER GetRegenRateScrollKnowledgeEquiv (sheet-worker.js:96419)
	function GetRegenRateScrollKnowledgeEquiv(tempPractitionerTitle) { // works for Scroll Knowledge, Elemental Knowledge, Hermetic Lore, Lightfire Knowledge, Shadowfrost Knowledge
		tempRegenRate="";
			switch(tempPractitionerTitle) {
				case 0: tempRegenRate="1/per Hour"; break;
				case 1: tempRegenRate="1/per Minute"; break;
				case 2: tempRegenRate="1/per 30 Seconds"; break;
				case 3: tempRegenRate="1/per 10 Seconds"; break;
				case 4: tempRegenRate="1/per 5 Seconds"; break;
				case 5: tempRegenRate="1/per 2 Seconds"; break;
				case 6: tempRegenRate="1/per Second"; break;
				case 7: tempRegenRate="2/per Second"; break;
				case 8: tempRegenRate="3/per Second"; break;
				case 9:
				case 10: tempRegenRate="4/per Second"; break;
				case 11:
				case 12:
				case 13:
				case 14:
				case 15:
				case 16:
				case 17:
				case 18:
				case 19:
				case 20:
				case 21:
				case 22:
				case 23:
				case 24:
				case 25:
				case 26:
				case 27:
				case 28:
				case 29:
				case 30: tempRegenRate="5/per Second"; break;
			}
		return tempRegenRate;
	}

// @MARKER GetRegenRateSecondaryEquiv (sheet-worker.js:96457)
	function GetRegenRateSecondaryEquiv(tempPractitionerTitle) { // works for Illusion Knowledge, Kinetics Knowledge
		tempRegenRate="";
			switch(tempPractitionerTitle) {
				case 0: tempRegenRate="1/per Hour"; break;
				case 1: tempRegenRate="1/per 5 Seconds"; break;
				case 2:
				case 3: tempRegenRate="1/per 2 Seconds"; break;
				case 4:
				case 5: tempRegenRate="1/per Second"; break;
				case 6: tempRegenRate="2/per Second"; break;
				case 7: tempRegenRate="3/per Second"; break;
				case 8: tempRegenRate="4/per Second"; break;
				case 9: tempRegenRate="5/per Second"; break;
				case 10: tempRegenRate="6/per Second"; break;
				case 11:
				case 12:
				case 13:
				case 14:
				case 15:
				case 16:
				case 17:
				case 18:
				case 19:
				case 20:
				case 21:
				case 22:
				case 23:
				case 24:
				case 25:
				case 26:
				case 27:
				case 28:
				case 29:
				case 30: tempRegenRate="7/per Second"; break;
			}
		return tempRegenRate;
	}

// @MARKER GetRegenRateWildMagic (sheet-worker.js:96495)
	function GetRegenRateWildMagic(tempPractitionerTitle) { // works for Wild Magic only
		tempRegenRate="";
			switch(tempPractitionerTitle) {
				case 0: tempRegenRate="1/per Hour"; break;
				case 1: tempRegenRate="1/per 10 Minutes"; break;
				case 2: tempRegenRate="1/per Minute"; break;
				case 3: tempRegenRate="1/per 30 Seconds"; break;
				case 4: tempRegenRate="1/per 10 Seconds"; break;
				case 5: tempRegenRate="1/per 5 Seconds"; break;
				case 6: tempRegenRate="1/per 2 Seconds"; break;
				case 7: tempRegenRate="1/per Second"; break;
				case 8: tempRegenRate="2/per Second"; break;
				case 9:
				case 10: tempRegenRate="3/per Second"; break;
				case 11:
				case 12:
				case 13:
				case 14:
				case 15:
				case 16:
				case 17:
				case 18:
				case 19:
				case 20:
				case 21:
				case 22:
				case 23:
				case 24:
				case 25:
				case 26:
				case 27:
				case 28:
				case 29:
				case 30: tempRegenRate="4/per Second"; break;
			}
		return tempRegenRate;
	}

// @MARKER addHighAuraRegenBoost (sheet-worker.js:96533)
	function addHighAuraRegenBoost(tempAuraRegenRate, tempAuraRegenBonus) {
		tmpNewAuraRegen="";
		if (tempAuraRegenRate.includes("per Second")) { // we will add to the seconds. 
			tmpStandardRegenNum=parseInt(tempAuraRegenRate.match(/\d+/)?.shift());
			tempAuraRegenBonus=tempAuraRegenBonus.slice(1);
			tmpModBoostNum=parseInt(tempAuraRegenBonus.match(/\d+/)?.shift());			
			newModNum=parseInt([tmpStandardRegenNum+tmpModBoostNum]);
			tmpNewAuraRegen=""+newModNum+"/per Second";
		} else {  // the High Aura regen boost is way over the current one and so supplants it. 
			tmpNewAuraRegen=tempAuraRegenBonus;
		}
		return tmpNewAuraRegen;
	}

// @MARKER getDoubleRegenRate (sheet-worker.js:96547)
	function getDoubleRegenRate(tempAuraRegenRate) {
		tmpDoubledRate="";
		switch (tempAuraRegenRate) {
			case "1/per Hour":
				tmpDoubledRate="2/per Hour";
				break;
			case "1/per 10 Minutes":
				tmpDoubledRate="2/per 10 Minutes";
				break;		
			case "1/per Minute":
				tmpDoubledRate="2/per Minute";
				break;
			case "1/per 30 Seconds":
				tmpDoubledRate="2/per 30 Seconds";
				break;
			case "1/per 10 Seconds":
				tmpDoubledRate="2/per 10 Seconds";
				break;
			case "1/per 5 Seconds":
				tmpDoubledRate="2/per 5 Seconds";
				break;
			case "1/per 2 Seconds":
				tmpDoubledRate="1/per Second";
				break;
			case "1/per Second":
				tmpDoubledRate="2/per Second";
				break;
			case "2/per Second":
				tmpDoubledRate="4/per Second";
				break;
			case "3/per Second":
				tmpDoubledRate="6/per Second";
				break;
			case "4/per Second":
				tmpDoubledRate="8/per Second";
				break;
			case "5/per Second":
				tmpDoubledRate="10/per Second";
				break;
			case "6/per Second":
				tmpDoubledRate="12/per Second";
				break;
			case "7/per Second":
				tmpDoubledRate="14/per Second";
				break;
			case "8/per Second":
				tmpDoubledRate="16/per Second";
				break;
			case "9/per Second":
				tmpDoubledRate="18/per Second";
				break;
			case "10/per Second":
				tmpDoubledRate="20/per Second";
				break;
			case "11/per Second":
				tmpDoubledRate="22/per Second";
				break;
			case "12/per Second":
				tmpDoubledRate="24/per Second";
				break;
			case "13/per Second":
				tmpDoubledRate="26/per Second";
				break;
			case "14/per Second":
				tmpDoubledRate="28/per Second";
				break;
			case "15/per Second":
				tmpDoubledRate="30/per Second";
				break;
			case "16/per Second":
				tmpDoubledRate="32/per Second";
				break;
			case "17/per Second":
				tmpDoubledRate="34/per Second";
				break;
			case "18/per Second":
				tmpDoubledRate="36/per Second";
				break;
			case "19/per Second":
				tmpDoubledRate="38/per Second";
				break;
			case "20per Second":
				tmpDoubledRate="40/per Second";
				break;
		}		
		return tmpDoubledRate;
	}

// @MARKER getMaxAuraControl (sheet-worker.js:99564)
	export function getMaxAuraControl(tempTitle) {
		tempMaxAC=0;
		switch (tempTitle) {
			case 1:
			case 2:
			case 3:
			case 4:
			case 5:
			case 6:
			case 7:
			case 8:
			case 9:
			case 10:
				tempMaxAC=25;
				break;
			case 11:
				tempMaxAC=26;
				break;
			case 12:
				tempMaxAC=27;
				break;
			case 13:
				tempMaxAC=28;
				break;
			case 14:
				tempMaxAC=29;
				break;
			case 15:
				tempMaxAC=30;
				break;
			case 16:
			case 17:
			case 18:
			case 19:
			case 20:
				tempMaxAC=50;
				break;
			case 21:
			case 22:
			case 23:
			case 24:
			case 25:
				tempMaxAC=75;
				break;
			case 26:
			case 27:
			case 28:
			case 29:
				tempMaxAC=100;
				break;
			case 30:
				tempMaxAC=1000;
				break;
		}
		return tempMaxAC;
	}

// @MARKER getMaxAuraPool (sheet-worker.js:99621)
	export function getMaxAuraPool(tempTitle,tempAuraRating) {
		tempMaxAP=0;
		switch (tempTitle) {
			case 1:
			case 2:
			case 3:
			case 4:
			case 5:
			case 6:
			case 7:
			case 8:
			case 9:
			case 10:
			case 11:
				tempMaxAP=parseInt((tempAuraRating*2))||0;
				break;
			case 12:
				tempMaxAP=60;
				break;
			case 13:
				tempMaxAP=70;
				break;
			case 14:
				tempMaxAP=80;
				break;
			case 15:
				tempMaxAP=90;
				break;
			case 16:
			case 17:
			case 18:
			case 19:
			case 20:
				tempMaxAP=100;
				break;
			case 21:
			case 22:
			case 23:
			case 24:
			case 25:
				tempMaxAP=500;
				break;
			case 26:
			case 27:
			case 28:
			case 29:
				tempMaxAP=750;
				break;
			case 30:
				tempMaxAP=1000;
				break;
		}
		return tempMaxAP;
	}

// @MARKER checkDevotion (sheet-worker.js:152688)
	export function checkDevotion(tempInvocationName, tmpCurrentDevotion) {
		tempFoundIn=false;
		devotionList=getDevotionList(tmpCurrentDevotion);
		devotionListArray=devotionList.split(",");
		for (var i=0; i<devotionListArray.length; i++) {
			if (tempInvocationName==devotionListArray[i])  {
				tempFoundIn=true;
				i=devotionListArray.length;
			}
		}
		return tempFoundIn;
	}

// @MARKER getDevotionList (sheet-worker.js:152701)
	export function getDevotionList(tmpCurrentDevotion) {
		tmpDevotionList="";
		switch (tmpCurrentDevotion) {
			default:
			case "":
				tmpDevotionList="";
				break;
			case "Body":
				tmpDevotionList="Thunderous Voice,Carry Voice,Breath of the Turtle,Eyes of the Dire Wolf,Eyes of the Eagle,Inner Fire,Levitate,Night Vision,Shadow Wings,Heal,Inhibit Smell,Tongue of the Serpent,Clumsy,Deafen,Enhanced Metabolism,Freedom,Hover Wings,Hydrate,Nourish,Remove Fatigue,Spirit of the Bloodhound,Staunch Blood,Tongues,Infuse Soma,Guard Body,High Pain Threshold,Shadow Adherence,Silence,Spirit Adherence,Vitalize,Shadow Might,Spirit of the Donkey,Center,Diffuse Soma,Guard Personal,Sustenance,Living Death,Malaise,Spirit of the Cheetah,Ailment,Blindness,Cause Fatigue,Mobility,Spirit of the Bear,Spirit of the Horse,Spirit of the Monkey,Elemental Water Form,Calcify Form,Consume Flesh,Elemental Water Form,Heart Burst,Petrify Form,Spirit Shift,Physical Renewal,Rebuke,Elemental Earth Form,Day Ken,Night Ken,Elemental Fire Form";
				break;
			case "Celestial":
				tmpDevotionList="Darkness,Light,Thunderous Voice,Carry Voice,Hands of Light,Spiritual Shield,Spiritual Writ,Tendrils of Darkness,Raiment,Spiritual Fist,Blessed Drink,Corrupted Drink,Hover Wings,Divine Weapon,Hands of Binding Light,Light of Sanctity,Shadow of Enmity,Tendrils of Grasping Darkness,Blessed Light,Cursed Light,Spiritual Messenger,Guard Personal,Light of Protection,Shadow of Weakness,Spirit Porter,Spirit Shackles,Spiritual Rowers,Wall of Darkness,Wall of Light,Divine Might,Hands of Defending Light,Spiritual Riding Beast,Tendrils of Offending Darkness,Eclipse,Blessed Ground,Cursed Ground,Spiritual Armor,Spiritual Crew,Spiritual Guide,Anguish,Bravery,Folly,Fortune,Divine Strike,Hands of Blinding Light,Light of Heroism,Shadow of Doom,Spiritual Guardian,Spiritual Warrior,Tendrils of Suffocating Darkness,Blinding Darkness,Divine Right,Enrich,Impoverish,Fanatic Fervor,Holy Touch,Unholy Touch,Calcify Form,Insidious Darkness,Intrepid Brilliance,Light of Banishment,Petrify Form,Shadow of Banishment,Sanctified Union,Doom,Hands of Overarching Light,Heroism,Suffocating Darkness,Rebuke,Tendrils of Overwhelming Darkness,Divine Wind,True Day,True Night,Light of Communion,Denial,Divine Blast,Divine Retribution,Shadow of Supplication,Summon Remains,Doomed Ground,Reviving Ground,Avatar,Divine Wrath,Hand of the Divine,Light of the Ascent,Miracle,Restore,Ruin,Shadow of the Fall,Spirit Form,True Denial,Hallowed Brand";
				break;
			case "Combat":
				tmpDevotionList="Deflect,Spiritual Shield,Harm,Spiritual Fist,Shroud of Ice,Aggression,Deafen,Blinding Strike,Clumsy,Freedom,Guided Strike,Refocus,Remove Fatigue,Spasm,Staunch Blood,Crack Leather,Divine Weapon,Guard Body,High Pain Threshold,Restore Leather,Share Pain,Shroud of Flame,Break Limb,Calm,Choking Grasp,Dizzy,Panic,Center,Diffuse Soma,Earthskin,Restore Wood,Shroud of Electricity,Warp Wood,Divine Might,Hands of Defending Light,Tendrils of Offending Darkness,Blindness,Brittle Bone,Cause Fatigue,Corrode Metal,Mobility,Shared Sacrifice,Shroud of Acid,Spiritual Armor,Transfer Soma,Woodskin,Anguish,Bravery,Hands of Blinding Light,Light of Heroism,Material Warrior Defender,Rockskin,Shadow of Doom,Shroud of Chaos,Spiritual Warrior,Tendrils of Suffocating Darkness,Dance,Disharmony,Frostbrand,Harmony,Judgment,Firebrand,Shroud of Death,Steelskin,Arcbrand,Hands of Overarching Light,Rebuke,Tendrils of Overwhelming Darkness,Living Judgment,Acidbrand,Crystalskin,Chaosbrand,Bane,Blood Reave,Empyreal Triumph,Eye for an Eye,Hallowed Brand,Profane Brand";
				break;
			case "Control":
				tmpDevotionList="Hold Plant,Plant Possession,Control Plant,Hold Animal,Animal Possession,Frenzy,Hold,Aggression,Control Animal,Control Water Elemental,Hold Magical Plant,Calm,Panic,Hold Magical Animal,Dizzy,Balk,Control Air Elemental,Control Humanoid,Detect Influence,Enmity,Friendship,Share Suffering,Halt Spirit,Affinity,Aversion,Control Undead,Fear,Fortitude,Control Slime,Torment,Absolve Control,Control Earth Elemental,Control Magical Plant,Hold Magical Humanoid,Control Magical Animal,Control Fire Elemental,Control Magical Humanoid,Control Death Elemental,Control Life Elemental,Dance,Disharmony,Divine Right,Harmony,Geas,Vice,Virtue,Corruption,Direct,Sanctity,Denial,Living Word,Apply Disability,Disable Immunity,Revocation,True Denial";
				break;
			case "Divination":
				tmpDevotionList="Detect Temperature,Detect Corpse,Discern Wounds,Read,Detect Evil,Detect Good,Eyes of the Dire Wolf,Eyes of the Eagle,Night Vision,Comprehension,Detect Enemy,Sign,Presence,Tongue of the Serpent,Fate Token,Tongues,Discern Disease,Divine Sight,Pathfind,Shadow Sight,Detect Divinity,Detect Supernatural,Detect Influence,Discern Motivation,Last Thought,Discern Poison,Spiritual Guide,Discern Divinity,Hand of the Divine,Spirit Echo";
				break;
			case "Elemental":
				tmpDevotionList="Airwall,Breeze,Create Water,Float,Light,Parch,Inner Fire,Smother Flame,Shroud of Ice,Waterwalk,Control Water Elemental,Shroud of Flame,Control Air Elemental,Earthskin,Material Messenger,Material Porter,Shroud of Electricity,Tremor,Calm Winds,Dimensional Barricade,Wall of Wind,Cleansing Winds,Control Earth Elemental,Material Animal Guardian,Shroud of Acid,Wall of Earth,Call Lightning,Calm Seas,Wall of Water,Control Fire Elemental,Constrain Temperature,Elemental Water Form,Hailstorm,Material Warrior Defender,Quagmire,Rockskin,Shroud of Chaos,Summon Water Elemental,Boil Earth,Calm Storms,Frostbrand,Control Weather,Elemental Air Form,Summon Air Elemental,Firebrand,Steelskin,Arcbrand,Crystalskin,Divine Wind,Elemental Earth Form,Summon Earth Elemental,Sinkhole,Elemental Fire Form,Molten Earth,Summon Fire Elemental,Earthquake,Tornado";
				break;
			case "General":
				tmpDevotionList="Chill,Clean,Purify Food,Purify Water,Wind Voice,Create Food,Create Water,Darkness,Float,Light,Read,Deflect,Hands of Light,Levitate,Smother Flame,Spiritual Writ,Tendrils of Darkness,Comprehension,Detect Enemy,Hold,Sign,Raiment,Hydrate,Nourish,Sanctuary,Tongues,Waterwalk,Hands of Binding Light,Infuse Soma,Shadow Adherence,Silence,Spirit Adherence,Tendrils of Grasping Darkness,Detect Divinity,Detect Supernatural,Sphere of Silence,Discern Motivation,Material Messenger,Material Porter,Phase Shackles,Shadow Shackles,Spirit Porter,Spirit Shackles,Spiritual Rowers,Sustenance,Aphasia,Dimensional Barricade,Hands of Defending Light,Spiritual Riding Beast,Tendrils of Offending Darkness,Hold Magical Humanoid,Planar Hold,Spirit Cage,Wall of Protection,Discern Divinity,Hands of Blinding Light,Sphere of Protection,Tendrils of Suffocating Darkness,Dimensional Blockade,Spirit Wall,Dispel Divinity,Geas,Hands of Overarching Light,Spirit Shift,Tendrils of Overwhelming Darkness,Word of Passage,Imprison,Spirit Sphere,Vice,Virtue,Twist of Fate,Anti-Magic,Denial,Summon Remains,Permanency,Plane Shift,Turn Divinity,Avatar,Compact,Conditional Divinity Imbuement,Covenant,Hand of the Divine,Imbue Divinity,Investment,Oathbreak,Planar Lock,True Denial";
				break;
			case "Healing":
				tmpDevotionList="Clean,Preservation,Purify Food,Purify Water,Warm,Discern Wounds,Light,Waken,Detect Evil,Heal,Halt Decay,Blessed Drink,Disguise Life Force,Hydrate,Nourish,Refocus,Remove Fatigue,Staunch Blood,Discern Disease,Infuse Soma,Light of Sanctity,Restore Leather,Share Pain,Vitalize,Blessed Light,Calm,Cure Blindness,Balk,Guard Personal,Halt Spirit,Light of Protection,Protection from Undead,Restore Wood,Share Suffering,Sustenance,Wall of Light,Discern Poison,Restore Sanity,Living Death,Absolve Control,Blessed Ground,Brittle Bone,Cure,Incorruptible Form,Light of Life,Morgue,Restore Bone,Restore Form,Restore Metal,Share Deformity,Shared Sacrifice,Transfer Soma,Light of the Living,Living Earth,Rejuvenate,Guard Soul,Life Sleep,Share Sorrow,Surcease,Control Life Elemental,Enrich,Holy Touch,Personal Renewal,Reclaim Sanity,Spirit Flow,Incorruptible Spirit,Intrepid Brilliance,Regeneration,Shroud of Death,Succor Allies,Wall of Life,Renascence,Isolation,Release,Physical Renewal,Incorruptible Soul,Living Judgment,True Day,Light of Restoration,Circle of Life,Fertilization,Mental Renewal,Mercy,Living Word,Restore Soul,Slow Death,Vanquish Undead,Elemental Life Form,Extend Life,Lifebrand,Mystical Renewal,Reincarnation,Remedy,Reviving Ground,Summon Life Elemental,Martyr";
				break;
			case "Mind":
				tmpDevotionList="Plant Possession,Read,Animal Possession,Comprehension,Frenzy,Aggression,Nightmare,Tongues,Mind Touch,Calm,Insomnia,Panic,Unpresence,Balk,Control Humanoid,Detect Influence,Discern Motivation,Last Thought,Enmity,Friendship,Share Suffering,Affinity,Aphasia,Aversion,Fear,Fortitude,Restore Sanity,Torment,Absolve Control,Guard Mind,Feral Instinct,Control Magical Humanoid,Disharmony,Fanatic Fervor,Reclaim Sanity,Stupor,Delirium,Clarity,Corruption,Horrors,Mental Renewal,Possession,Sanctity,Spirit Echo";
				break;
			case "Nature":
				tmpDevotionList="Chill,Create Food,Create Water,Hold Plant,Plant Speak,Ripen Scent,Warm,Wind Voice,Airwall,Animal Speak,Breeze,Parch,Plant Possession,Shroud Scent,Breath of the Turtle,Control Plant,Eyes of the Dire Wolf,Eyes of the Eagle,Hold Animal,Inner Fire,Night Vision,Protection from Plants,Smother Flame,Animal Possession,Entwine,Inhibit Smell,Plant Move,Protection from Animals,Tongue of the Serpent,Frenzy,Control Animal,Enhanced Metabolism,Plant Growth,Protection from Slime,Spirit of the Bloodhound,Summon Animal,Waterwalk,Crack Leather,Pathfind,Silence,Hold Magical Plant,Protection from Magical Plants,Restore Leather,Vitalize,Animal Messenger,Hold Magical Animal,Spirit of the Donkey,Earthskin,Material Messenger,Material Porter,Protection from Magical Animals,Restore Wood,Tremor,Wall of Thorns,Warp Wood,Wall of Wind,Aspect of the Beast,Calm Winds,Control Slime,Spirit of the Cheetah,Animal Growth,Cleansing Winds,Control Magical Plant,Corrode Metal,Material Animal Guardian,Restore Metal,Spirit of the Bear,Spirit of the Horse,Spirit of the Monkey,Swarm Shape,Wall of Earth,Woodskin,Call Lightning,Calm Seas,Control Magical Animal,Feral Instinct,Thunderclap,Wall of Water,Constrain Temperature,Hailstorm,Life Sleep,Material Warrior Defender,Quagmire,Rockskin,Calm Storms,Boil Earth,Control Weather,Steelskin,Tree Form,True Twilight,Skin to Beast,Day Ken,Divine Wind,Crystalskin,Night Ken,Fertilization,Pestilence,Sinkhole,Molten Earth,Insect Swarm,Protection from Nature,Earthquake,Reincarnation,Tornado,Climate Change";
				break;
			case "Necromancy":
				tmpDevotionList="Chill,Contaminate Water,Putrefy Food,Tarnish,Darkness,Detect Corpse,Parch,Wither Food,Detect Good,Mummify,Shadow Wings,Harm,Aggression,Disguise Life Force,Corrupted Drink,Nightmare,Crack Leather,Shadow Adherence,Shadow Sight,Shadow of Enmity,Siphon Soma,Choking Grasp,Cursed Light,Panic,Shadow Might,Coexist with Undead,Last Thought,Shadow of Weakness,Wall of Darkness,Warp Wood,Control Undead,Eclipse,Malaise,Stench of Decay,Torment,Ailment,Brittle Bone,Cause Fatigue,Corrode Metal,Corruptible Form,Cursed Ground,Restore Bone,Shadow of Death,Swarm Shape,Animate Bone,Animate Flesh,Dying Earth,Wall of Bone,Shadow Shroud,Scourge,Blinding Darkness,Control Death Elemental,Create Undead Spirit,Impoverish,Spirit Leak,Unholy Touch,Consume Flesh,Corruptible Spirit,Heart Burst,Insidious Darkness,Shadow of Banishment,Summon Undead,Wall of Death,Create Greater Undead,Reconstitute,Shadow Shift,Suffocating Darkness,Corruptible Soul,Shadow of Ruination,True Night,Circle of Death,Create Greater Undead Spirit,Pestilence,Deathbrand,Doomed Ground,Elemental Death Form,Ravage,Summon Death Elemental,Undead Swarm,Blood Reave,Conquest of the Eternal,Plague,Profane Brand";
				break;
			case "Protection":
				tmpDevotionList="Airwall,Shroud Scent,Deflect,Inner Fire,Mummify,Protection from Plants,Self-Control,Spiritual Shield,Protection from Animals,Halt Decay,Shroud of Ice,Disguise Life Force,Freedom,Protection from Slime,Sanctuary,Guard Body,High Pain Threshold,Light of Sanctity,Protection from Magical Plants,Shroud of Flame,Blessed Light,Cursed Light,Calm,Insomnia,Sphere of Silence,Unpresence,Center,Coexist with Undead,Earthskin,Guard Personal,Light of Protection,Protection from Magical Animals,Protection from Undead,Shroud of Lifelessness,Shroud of Electricity,Aversion,Dimensional Barricade,Fortitude,Blessed Ground,Guard Mind,Incorruptible Form,Material Animal Guardian,Morgue,Shroud of Acid,Spiritual Armor,Wall of Protection,Woodskin,Reflect Divinity,Constrain Temperature,Guard Soul,Rockskin,Sphere of Protection,Spiritual Guardian,Shroud of Chaos,Dimensional Blockade,Fanatic Fervor,Harmony,Incorruptible Spirit,Shroud of Death,Heroism,Resolve,Second Chance,Incorruptible Soul,Word of Passage,Vampiric Shroud,Clarity,Death Shroud,Anti-Magic,Denial,Guard Self,Protection from Nature,Grant Ability,Grant Immunity,True Denial";
				break;
			case "Summoning":
				tmpDevotionList="Clean,Airwall,Breeze,Create Food,Create Water,Parch,Wither Food,Hands of Light,Spiritual Shield,Shadow Wings,Smother Flame,Tendrils of Darkness,Raiment,Shroud of Ice,Blessed Drink,Corrupted Drink,Summon Animal,Control Water Elemental,Hands of Binding Light,Shroud of Flame,Tendrils of Grasping Darkness,Animal Messenger,Detect Supernatural,Spiritual Messenger,Control Air Elemental,Material Messenger,Material Porter,Phase Shackles,Shadow Shackles,Shroud of Electricity,Spirit Porter,Spirit Shackles,Spiritual Rowers,Wall of Darkness,Wall of Light,Wall of Thorns,Spiritual Riding Beast,Calm Winds,Dimensional Barricade,Hands of Defending Light,Tendrils of Offending Darkness,Wall of Wind,Bind Origin,Cleansing Winds,Control Earth Elemental,Material Animal Guardian,Planar Hold,Return to Origin,Spiritual Armor,Spirit Cage,Spiritual Crew,Spiritual Guide,Wall of Protection,Wall of Earth,Wall of Bone,Wall of Water,Control Fire Elemental,Hands of Blinding Light,Material Warrior Defender,Sphere of Protection,Spiritual Guardian,Spiritual Warrior,Summon Water Elemental,Tendrils of Suffocating Darkness,Dimensional Blockade,Control Death Elemental,Control Life Elemental,Frostbrand,Firebrand,Light of Banishment,Shadow of Banishment,Spirit Wall,Summon Air Elemental,Summon Undead,Wall of Death,Wall of Life,Hands of Overarching Light,Likeness Spirit Draw,Release,Arcbrand,Shadow Shift,Spirit Shift,Tendrils of Overwhelming Darkness,Acidbrand,Imprison,Spirit Sphere,Summon Earth Elemental,Chaosbrand,Insect Swarm,Summon Fire Elemental,Summon Remains,Deathbrand,Plane Shift,Lifebrand,Avatar,Hallowed Brand,Planar Lock,Profane Brand,Spirit Echo";
				break;
		}
		return tmpDevotionList;
	}

// @MARKER getHalfCastingTime (sheet-worker.js:170511)
	export function getHalfCastingTime(tempSpellCastTime) {
		tempNewCastingTime="";
		tempCastTimeValue=parseInt(tempSpellCastTime);
		tempCastTimeValue2=parseFloat(tempCastTimeValue+0.9);
		tempCastTimeType=tempSpellCastTime.replace(""+tempCastTimeValue+" ","");
		newCastTimeValue=divideWithMin(tempCastTimeValue2, 2);
		tempNewCastingTime=""+newCastTimeValue+" "+tempCastTimeType;
		return tempNewCastingTime;
	}

// @MARKER getLightFireSpellsWithoutLevel (sheet-worker.js:171376)
	export function getLightFireSpellsWithoutLevel() {
		lightFireSpells=[ "Color","Flicker","Produce Light","Warm","Endure Light","Produce Fire","Ignite","Phase Adhere","Circle of Fire","Finger of Fire","Wall of Light","Enhance Sight","Manipulate Light","Phase Weapon","Storm of Daggers","Duplicate Self","Endure Heat","Invisibility","Storm of Fire","Wall of Fire","Storm of Arrows","Unphase","Absorb Heat","Aura of Fire","Brilliance","Phase","Storm of Spears","Incinerate","Storm of Bolts","Mass Invisibility" ];
		return lightFireSpells;
	}

// @MARKER getAllShadowFrostSpellsWithoutLevel (sheet-worker.js:171461)
	export function getAllShadowFrostSpellsWithoutLevel() {
		shadowFrostSpells=[ "Chill","Night Vision","Fast Freeze","Shade Touch","Shadowless","Circle of Cold","Darkness","Finger of Cold","Shadow Adhere","Blind","Distortion","Endure Cold","Fade","Storm of Cold","Wall of Darkness","Ice Swim","Manipulate Shadow","Shadow Weapon","Wall of Ice","Absorb Cold","Aura of Ice","Control Temperature","Shadow Shift","Ice Form","Shadow Attack" ];
		return shadowFrostSpells;
	}

// @END (CODE)
